const { test, expect } = require('@playwright/test');
const { createNewUserInfo } = require('../../utils/user');
const { VIEWPORTS } = require('../../helpers/auth');
const { fillPaymentIframe } = require('../../utils/payment');
const { fillMFACode } = require('../../utils/mfa');

test.describe('B2C', () => {
  test.describe.configure({ mode: 'parallel' });
  test.beforeEach(async ({ page }) => {
    await page.context().clearCookies();
    await page.setViewportSize(VIEWPORTS['macbook-15']);
    await page.goto('/');
  });

  test('should create a new b2c trial account', async ({ page }) => {
    test.setTimeout(120000);
    const newUser = createNewUserInfo({ type: 'b2cTrial' });
    await page.goto('/start-trial/');
    await page.locator('input[name="first_name"]').fill(newUser.firstName);
    await page.locator('input[name="last_name"]').fill(newUser.lastName);
    await page.locator('input[name="email"]').fill(newUser.email);
    await page.locator('input[name="password"]').fill(newUser.password);
    await page.locator('[name="t_c_agreement"]').click();
    await page.getByText('Start free trial').click();
    await fillMFACode(page);
    await page.locator('[data-testid="toggle-popover-my-oreilly"]').waitFor({ timeout: 60000 });
    await page.goto('p/subscribe/');
    await expect(page.getByTestId('alertContainer')).toContainText("You are currently previewing the O\u2019Reilly Learning Platform.");
  });

  test('should create a new trial account with GDPR and a Monthly Subscription with a VAT exemption', async ({ page }) => {
    test.setTimeout(180000);
    const newUser = createNewUserInfo({ type: 'b2cTrial_Subscribe' });
    await page.goto('/start-trial/');
    await page.locator('input[name="first_name"]').fill(newUser.firstName);
    await page.locator('input[name="last_name"]').fill(newUser.lastName);
    await page.locator('input[name="email"]').fill(newUser.email);
    await page.locator('input[name="password"]').fill(newUser.password);
    await page.locator('[name="t_c_agreement"]').click();
    await page.getByText('Start Free Trial').click();
    await fillMFACode(page);
    await page.locator('[data-testid="toggle-popover-my-oreilly"]').waitFor({ timeout: 60000 });
    await page.goto('p/subscribe/');
    await expect(page.getByTestId('alertContainer')).toContainText("You are currently previewing the O\u2019Reilly Learning Platform.");
    await page.locator('select[name="currencySelect"]').selectOption('Euro €');
    await page.getByText('Monthly', { exact: true }).waitFor();
    await page.getByText('Monthly', { exact: true }).click();
    await page.locator('select[name="billingCountry"]').selectOption('France');
    await page.locator('input[name="billingAddress"]').waitFor();
    await page.locator('input[name="billingAddress"]').fill('1 Main Street');
    await page.locator('input[name="billingCity"]').fill('Paris');
    await page.locator('input[name="billingPostalCode"]').fill('75000');
    await page.getByText('Apply a VAT exemption number').click();
    await page.locator('input[name="vatExemptionNumber"]').fill('No Vat For Me');
    await page.getByText('Continue').first().click({ force: true });
    await fillPaymentIframe(page, { expMonth: '12', expYear: '2027' });
    await expect(page.locator('body')).toContainText("Success! You are subscribed to the O\u2019Reilly Learning Platform.", { timeout: 60000 });
    await page.getByRole('link', { name: 'Plans & Payment' }).waitFor();
    await page.getByRole('link', { name: 'Plans & Payment' }).click();
    await page.getByText('Trial Plan, €0').click();
    await expect(page.getByText('You will next be billed for a Monthly plan at a rate of €43 (plus applicable tax/VAT) on').first()).toBeVisible();
  });

  test('should create a new paid user from Signup with GDPR, Promotion Code, VAT Charged, and a Payment update', async ({ page }) => {
    test.setTimeout(180000);
    const newUser = createNewUserInfo({ type: 'b2cSignupPromoVat' });
    await page.goto('signup/?promotion_code=flashsale21');
    await page.locator('select[name="currencySelect"]').selectOption('EUR');
    await page.getByRole('radio', { name: /Annual/ }).click();
    await page.getByText('Continue').first().click({ force: true });
    await page.locator('input[name="first_name"]').waitFor();
    await page.locator('input[name="first_name"]').fill(newUser.firstName);
    await page.locator('input[name="last_name"]').fill(newUser.lastName);
    await page.locator('input[name="email"]').fill(newUser.email);
    await page.locator('input[name="password"]').fill(newUser.password);
    await page.locator('select[name="country"]').selectOption('Ireland');
    await page.locator('[name="t_c_agreement"]').click();
    await page.getByText('Create account').click();
    await fillMFACode(page);
    await page.getByText('Credit or debit card', { exact: false }).first().click({ timeout: 60000 });
    await page.getByLabel('Postal or zip code').waitFor();
    await page.getByLabel('Postal or zip code').fill('D01 H104');
    await page.locator('select[name="field_creditCardCountry"]').selectOption('Ireland');
    await page.locator('input[name="creditCardAddress1"]').waitFor();
    await page.locator('input[name="creditCardAddress1"]').fill('1 Main Street');
    await page.locator('input[name="creditCardCity"]').fill('Dublin');
    await page.getByText('Continue').first().click();
    await expect(page.locator('[data-cy="cart-total"]')).toContainText('259');
    await fillPaymentIframe(page, { expMonth: '12', expYear: '2027' });
    await page.waitForURL(/home/, { timeout: 60000, waitUntil: 'domcontentloaded' });
    await page.goto('p/subscribe');
    await expect(page.getByText('You will be charged €433').first()).toBeVisible();
    await page.goto('p/billing-history/');
    await expect(page.getByText('€318.57').first()).toBeVisible();
    // Payment update
    await page.goto('p/subscribe/');
    await page.getByText('Update Payment').click();
    await page.getByLabel('Postal or ZIP code').fill('D01 H104');
    await page.locator('select[name="billingCountry"]').selectOption('Ireland');
    await page.locator('input[name="billingAddress"]').fill('1 Main Street');
    await page.locator('input[name="billingCity"]').fill('Dublin');
    await page.evaluate(() => document.getElementById('onetrust-consent-sdk')?.remove());
    await page.getByRole('button', { name: 'Continue' }).click();
    await fillPaymentIframe(page, { expMonth: '12', expYear: '2027' });
  });

  test('should create a new Monthly paid user whose Credit Card will expire next month', async ({ page }) => {
    test.setTimeout(180000);
    const newUser = createNewUserInfo({ type: 'b2cSignup_cc_expire' });
    await page.goto('signup/');
    await page.getByText('Monthly', { exact: true }).click();
    await page.getByText('Continue').first().click({ force: true });
    await page.locator('input[name="first_name"]').waitFor();
    await page.locator('input[name="first_name"]').fill(newUser.firstName);
    await page.locator('input[name="last_name"]').fill(newUser.lastName);
    await page.locator('input[name="email"]').fill(newUser.email);
    await page.locator('input[name="password"]').fill(newUser.password);
    await page.locator('[name="t_c_agreement"]').click();
    await page.locator('#create-account-button').click();
    await fillMFACode(page);
    await page.getByLabel('Postal or zip code').fill('90210');
    await page.getByText('Continue').first().click({ force: true });
    await fillPaymentIframe(page, { expMonth: '05', expYear: '2026' });
    await page.waitForURL(/home/, { timeout: 60000, waitUntil: 'domcontentloaded' });
    await page.goto('p/billing-history/');
    await expect(page.getByText('$49.00').first()).toBeVisible();
  });

  test('should create a new Annual paid user where billing country is India', async ({ page }) => {
    test.setTimeout(180000);
    const newUser = createNewUserInfo({ type: 'b2cSignup_cc_india' });
    await page.goto('signup/');
    await page.getByRole('radio', { name: /Annual/ }).click();
    await page.getByText('Continue').first().click({ force: true });
    await page.locator('input[name="first_name"]').waitFor();
    await page.locator('input[name="first_name"]').fill(newUser.firstName);
    await page.locator('input[name="last_name"]').fill(newUser.lastName);
    await page.locator('input[name="email"]').fill(newUser.email);
    await page.locator('input[name="password"]').fill(newUser.password);
    await page.locator('[name="t_c_agreement"]').click();
    await page.locator('#create-account-button').click();
    await fillMFACode(page);
    await page.getByLabel('Postal or zip code').fill('110003');
    await page.locator('select[name="field_creditCardCountry"]').selectOption('India');
    await page.locator('input[name="creditCardAddress1"]').waitFor();
    await page.locator('input[name="creditCardAddress1"]').fill('1 Main Street');
    await page.locator('input[name="creditCardCity"]').fill('New Delhi');
    await page.getByText('Continue').first().click();
    await page.locator('[data-cy="cart-total"]').waitFor();
    await page.getByText('Continue').first().click({ force: true });
    await fillPaymentIframe(page, { cardNumber: '4111111111111111', expMonth: '10', expYear: '2029' });
    await page.waitForURL(/home/, { timeout: 60000, waitUntil: 'domcontentloaded' });
    await page.goto('p/billing-history/');
    await expect(page.getByText('$588.82').first()).toBeVisible();
  });

  test('should create a new Three Month paid user that changes their Plan to Annual', async ({ page }) => {
    test.setTimeout(180000);
    const newUser = createNewUserInfo({ type: 'b2cSignup_changeplan' });
    await page.goto('signup/');
    await page.getByText('Three Month', { exact: true }).click();
    await page.getByText('Continue').first().click({ force: true });
    await page.locator('input[name="first_name"]').fill(newUser.firstName);
    await page.locator('input[name="last_name"]').fill(newUser.lastName);
    await page.locator('input[name="email"]').fill(newUser.email);
    await page.locator('input[name="password"]').fill(newUser.password);
    await page.locator('[name="t_c_agreement"]').click();
    await page.locator('#create-account-button').click();
    await fillMFACode(page);
    await page.getByLabel('Postal or zip code').fill('90210');
    await page.getByText('Continue').first().click({ force: true });
    await fillPaymentIframe(page, { expMonth: '10', expYear: '2029' });
    await page.waitForURL(/home/, { timeout: 60000, waitUntil: 'domcontentloaded' });
    await page.goto('p/billing-history/');
    await expect(page.getByText('$129.00').first()).toBeVisible();
    await page.goto('p/subscribe/');
    await page.getByText('Change Plan').click();
    await page.getByRole('radio', { name: /Annual/ }).click();
    await page.getByText('Confirm Change').click();
    await expect(page.locator('[data-testid="activeNextBill"]')).toContainText('You will be charged $499');
  });

  test('should create a new Monthly paid user that cancels', async ({ page }) => {
    test.setTimeout(180000);
    const newUser = createNewUserInfo({ type: 'b2cSignup_cancel' });
    await page.goto('signup/');
    await page.getByText('Monthly', { exact: true }).click();
    await page.getByText('Continue').first().click({ force: true });
    await page.locator('input[name="first_name"]').fill(newUser.firstName);
    await page.locator('input[name="last_name"]').fill(newUser.lastName);
    await page.locator('input[name="email"]').fill(newUser.email);
    await page.locator('input[name="password"]').fill(newUser.password);
    await page.locator('[name="t_c_agreement"]').click();
    await page.locator('#create-account-button').click();
    await fillMFACode(page);
    await page.getByLabel('Postal or zip code').fill('90210');
    await page.getByText('Continue').first().click({ force: true });
    await fillPaymentIframe(page, { expMonth: '01', expYear: '2030' });
    await page.waitForURL(/home/, { timeout: 60000, waitUntil: 'domcontentloaded' });
    await page.goto('p/billing-history/');
    await expect(page.getByText('$49.00').first()).toBeVisible();
    await page.goto('p/subscribe/');
    await expect(page.getByText('Monthly Plan, $49 per month').first()).toBeVisible();
    await page.getByText('Cancel Plan').click();
    await page.getByText('Finish Cancellation').click();
    await expect(page.getByText('Restart Membership').first()).toBeVisible();
    await expect(page.locator('[data-testid="pendingCancellationNextBill"]')).toContainText('Your membership will be cancelled on');
  });

  test('should create a new 30 Day Complimentary User', async ({ page }) => {
    test.setTimeout(120000);
    const newUser = createNewUserInfo({ type: 'b2cComp_30day' });
    await page.goto('get-learning/');
    await expect(page.getByText('Activate Your Membership').first()).toBeVisible();
    await page.getByRole('textbox', { name: 'First name' }).fill(newUser.firstName);
    await page.getByRole('textbox', { name: 'Last name' }).fill(newUser.lastName);
    await page.getByRole('textbox', { name: 'Email address' }).fill(newUser.email);
    await page.locator('input[type="password"]').fill(newUser.password);
    await page.getByRole('checkbox').click();
    await page.getByRole('textbox', { name: 'Promo code' }).fill('30day');
    await page.getByRole('button', { name: 'Activate account' }).click();
    await fillMFACode(page);
    await page.locator('[data-testid="toggle-popover-my-oreilly"]').waitFor({ timeout: 60000 });
    await page.goto('/p/subscribe/');
    await page.getByRole('link', { name: 'Plans & Payment' }).click();
    await expect(page.locator('body')).toContainText("Your Complimentary Access to the O\u2019Reilly Learning Platform will end on");
  });
});
